---
title: "analysis1"
output: html_document
date: "2024-08-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(viridis)
library(plotly)
library(scales)
library(pheatmap)
#install.packages("waffle", repos = "https://cinc.rud.is") 
library(reshape2)
#library(HDInterval)
library(rjags)
library(stringr)
library(tidyr)
library(tidybayes)

```

simulate some data

```{r}
set.seed(123)
dates <- seq.Date(from=as.Date('2022-01-01'), by='day', length.out=578)

 pm2_5 <- rnorm(n=length(dates),0,1)
 humidity <- rnorm(n=length(dates),0,1)
 
 rho=0.8
 ar1 <- NA
 ar1[1] <- rnorm(1,0,sd=0.2)
 
 for(i in 2:length(dates)){
   ar1[i] <- ar1[i-1]*rho +  rnorm(1,0,sd=0.2)
 }
 
 beta_dow <- c(-0.9,1,0.5, 0.4, 0.3, 0.3) #dow effect

 
 ds1 <- cbind.data.frame(dates, pm2_5, humidity,ar1) %>%
   mutate(day_of_week=as.factor(weekdays(dates)),
          pm2_5_lag0=pm2_5,
          pm2_5_lag1 =lag(pm2_5,1),
          pm2_5_lag2 =lag(pm2_5,2),
          pm2_5_lag3 =lag(pm2_5,3),
          pm2_5_lag4 =lag(pm2_5,4),
          pm2_5_lag5 =lag(pm2_5,5),
          pm2_5_lag6 =lag(pm2_5,6),
          pm2_5_lag7 =lag(pm2_5,7),
          pm2_5_lag8 =lag(pm2_5,8),
          pm2_5_lag9 =lag(pm2_5,9),
          pm2_5_lag10 =lag(pm2_5,10),
          pm2_5_lag11 =lag(pm2_5,11),
          pm2_5_lag12 =lag(pm2_5,12),
          pm2_5_lag13 =lag(pm2_5,13),
          pm2_5_lag14 =lag(pm2_5,14),
          ) %>%
   filter(!is.na(pm2_5_lag14))
 
 coef_pm2_5 <- c(0.01,0.02,0.02,0.01, 0.04, 0.08, 0.1, 0.2, 0.1,0.05,0.02,0.01,0.01, 0,0)
 coef_pm2_5 <- coef_pm2_5/sum(coef_pm2_5) #weight to 1

 pm2_5_mat <- ds1 %>%
   select(starts_with('pm2_5_lag')) %>%
   as.matrix()
 
 dow_mat <- model.matrix(~day_of_week, data=ds1) 
 dow_mat <- dow_mat[,-1] #remove intercept
 
 ds1$dow_part <- dow_mat %*% beta_dow
 
 ds1$pm2_5_part <- pm2_5_mat %*% coef_pm2_5
 
 ds1$lambda1 <- exp(2 + ds1$ar1 + ds1$dow_part + 0.5*ds1$pm2_5_part [,1])
 ds1$cases <- rpois(nrow(ds1), lambda=ds1$lambda1)
 
 
```



### Define the model 
```{r}

model_string <- "

model{
for(i in 1:Ntimes){

  cases[i] ~ dnegbin(prob[i],r)
  prob[i]<- r/(r+lambda[i])  ## likelihood 

  log(lambda[i]) <-   alpha[i] +inprod(delta[],dow_mat[i,]) +
                    inprod(epsilon[],pm2_5_mat[i,])
  

}

#AR1 random intercept
  alpha[1] ~ dnorm(mu0  , (1 - rho1^2) * tau.alpha1) # Prior for the first time point
  for(i in 2:Ntimes){
    alpha[i] ~ dnorm( mu0  + rho1 * alpha[i-1], tau.alpha1)
  }
  
  #day of week effects
  for(k in 1:6){
    delta[k]~dnorm(0,1)
  }
  
  
  epsilon[1] ~ dnorm(0, (1 - rho2^2) * tau.epsilon2)
  for(m in 2:15){
    epsilon[m] ~ dnorm(rho2 *epsilon[m-1] , tau.epsilon2)
  }
  

  tau.alpha1 ~ dgamma(3, 2)  # Tight prior for tau 
  tau.epsilon2 ~ dgamma(3, 2)  # Tight prior for tau 

  rho1 ~ dunif(-1, 1)       # Uniform prior for rho
  rho2 ~ dunif(-1, 1)       # Uniform prior for rho

  mu0 ~ dnorm(0, 1e-4)   # Uninformative prior for intercept
  
  r ~ dunif(0,250)

}
"
```

### Set random seeds. 
We are going to run 3 chains in the MCMC, so we need a seed for each. This ensures reproducible results.

```{r}
inits1=list(".RNG.seed"=c(123), ".RNG.name"='base::Wichmann-Hill')
inits2=list(".RNG.seed"=c(456), ".RNG.name"='base::Wichmann-Hill')
inits3=list(".RNG.seed"=c(789), ".RNG.name"='base::Wichmann-Hill')
```

### Initialize the model
```{r}
model_spec<-textConnection(model_string)
model_jags<-jags.model(model_spec,
                       inits=list(inits1,inits2, inits3),
                       data=list('Ntimes'= nrow(ds1)  ,
                                 'cases'= ds1$cases,
                                 'pm2_5_mat'=pm2_5_mat,
                                 'dow_mat'=dow_mat
                                 
                       ),
                       n.adapt=2000,
                       n.chains=3, quiet=F)
```

### Posterior sampling

what parameters do you want to sample?
```{r}
params<-c('rho1', 'mu0','alpha','tau.alpha1','lambda', 'epsilon')

```

```{r}
posterior_samples<-coda.samples(model_jags, 
                                params, 
                                n.iter=2000)
```
## examine lambda
```{r}
test <- gather_draws(posterior_samples, lambda[i])

test %>%
  filter(i==1) %>%
  mutate(.chain=as.factor(.chain)) %>%
ggplot( aes(x=.iteration, y=.value, group=.chain, color=.chain), alpha=0.2) +
  geom_line()+
  theme_classic()


```

HDI for lambda
```{r}
lambda_quant <- test %>%
  median_hdi()

ggplot(lambda_quant, aes(x=i, y=.value)) +
  geom_line()+
  theme_minimal()
```


#AR1 component
```{r}
ar1_summary <- gather_draws(posterior_samples, alpha[i]) %>%
  median_hdi()

ggplot(ar1_summary, aes(x=i, y=.value)) +
  geom_line()+
  geom_ribbon(aes(x=i, ymin=.lower, ymax=.upper), alpha=0.2)+
  theme_minimal()

```



#base R extraction
```{r}
posterior_samples.all<-do.call(rbind,posterior_samples) #combine 3 chains into 1 data frame

post_means<-apply(posterior_samples.all, 2, mean)
sample.labs<-names(post_means)
ci<-t(hdi(posterior_samples.all, credMass = 0.95))
#ci<-matrix(sprintf("%.1f",round(ci,1)), ncol=2)
ci<-matrix(ci, ncol=2)

row.names(ci)<-sample.labs
#post_means<-sprintf("%.1f",round(post_means,1))
names(post_means)<-sample.labs

post_all <- cbind.data.frame(post_means,ci) 
names(post_all) <- c('pred','pred_lcl','pred_ucl')
post_all$param <- row.names(post_all)
```


